name: Computer

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        psp_mode: [LARGE_MEMORY=0]
        command_list: [COMMAND_LIST=0]
        adhoc: [ADHOC=0]
        save_state: [SAVE_STATE=0]
        emulator: [BUILD_MVS=1]

    steps:
    - uses: actions/checkout@v3

    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          git \
          wget \
          unzip \
          libbz2-dev \
          libsdl2-dev


    - name: Install Mac dependencies
      if: matrix.os == 'macOS-latest'
      run: |
        brew update
        brew install cmake sdl2 libzip

    - name: Compile project
      run: |
        mkdir build_mac
        cd build_mac
        cmake -DTARGET="MVS" -DPLATFORM="X86_64" ..
        make -j $(getconf _NPROCESSORS_ONLN)

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: NJEMU-${{ steps.slug.outputs.sha8 }}-${{ matrix.os }}-${{ matrix.psp_mode }}-${{ matrix.command_list }}-${{ matrix.adhoc }}-${{ matrix.save_state }}-${{ matrix.emulator }}
        path: |
          build_mac/MVS