name: PSP

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tag: [pspdev/pspdev]

    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add build-base git bash
    

    - name: Compile project
      run: |
        make clean
        make -j $(getconf _NPROCESSORS_ONLN)

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: NJEMU-${{ steps.slug.outputs.sha8 }}
        path: |
          SLIM
          3XX