name: PSP

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        psp_mode: [PSP_SLIM=0, PSP_SLIM=1]
        emulator: [
          BUILD_CPS1PSP=1 BUILD_CPS2PSP=0 BUILD_MVSPSP=0 BUILD_NCDZPSP=0,
          BUILD_CPS1PSP=0 BUILD_CPS2PSP=1 BUILD_MVSPSP=0 BUILD_NCDZPSP=0,
          BUILD_CPS1PSP=0 BUILD_CPS2PSP=0 BUILD_MVSPSP=1 BUILD_NCDZPSP=0,
          BUILD_CPS1PSP=0 BUILD_CPS2PSP=0 BUILD_MVSPSP=0 BUILD_NCDZPSP=1,
          ]

    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add build-base git bash
    

    - name: Compile project
      run: |
        make clean
        make -j $(getconf _NPROCESSORS_ONLN) ${{ matrix.psp_mode }} ${{ matrix.emulator }}

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: NJEMU-${{ steps.slug.outputs.sha8 }}-${{ matrix.psp_mode }}-${{ matrix.emulator }}
        path: |
          SLIM
          3XX