name: PSP

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        psp_mode: [LARGE_MEMORY=0, LARGE_MEMORY=1]
        command_list: [COMMAND_LIST=0, COMMAND_LIST=1]
        adhoc: [ADHOC=0] # ADHOC=1 is not working currently
        save_state: [SAVE_STATE=1, SAVE_STATE=0]
        emulator: [BUILD_CPS1=1, BUILD_CPS2=1, BUILD_MVS=1, BUILD_NCDZ=1]

    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add build-base git bash
    

    - name: Compile project
      run: |
        make clean ${{ matrix.emulator }}
        make -j $(getconf _NPROCESSORS_ONLN) ${{ matrix.psp_mode }} ${{ matrix.command_list }} ${{ matrix.adhoc }} ${{ matrix.save_state }} ${{ matrix.emulator }}

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: NJEMU-${{ steps.slug.outputs.sha8 }}-${{ matrix.psp_mode }}-${{ matrix.command_list }}-${{ matrix.adhoc }}-${{ matrix.save_state }}-${{ matrix.emulator }}
        path: |
          *.PBP