name: ROMCNV

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    name: ${{ matrix.target }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [CPS2, MVS]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          git \
          wget \
          unzip


    - name: Install Mac dependencies
      if: matrix.os == 'macOS-latest'
      run: |
        brew update
        brew install cmake libzip

    - name: Compile project
      run: |
        cd romcnv
        mkdir build
        cd build
        cmake \
          -DTARGET="${{ matrix.target }}" \
          ..
        make -j $(getconf _NPROCESSORS_ONLN)

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: ROMCNV-${{ steps.slug.outputs.sha8 }}-${{ matrix.os }}-${{ matrix.target }}
        path: |
          romcnv/build/